### ISSUE TITLE
Create db.py to create the MySQL database and grant privileges for pattoo

### ISSUE THREAD

**Issue by DangaRanga** [PalisadoesFoundation/pattoo#300]

**Comment by palisadoes** [comment]
One precaution. If the system administrator hasn’t granted write and create rights to pattoo’s configured database username, this will fail. A typical precaution is to only allow read/write access, not create rights to application users.

This is an example of where the code will need to gracefully fail and say, `insufficient privileges` and/or `unable to connect to the database` as part of a general error message.
