### ISSUE TITLE
Existing pattoo_server.yaml configuration overwritten by defaults

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/pattoo#344]
This looks like an error introduced in v93

**Comment by palisadoes** [comment]
It overwrites on reinstallation too

**Comment by DangaRanga** [comment]
Ah, so it's just supposed to overwrite if the configuration values aren't in the file instead of overwriting the file completely?

**Comment by palisadoes** [comment]
I've commented out the section that was causing the issue. It'll be simpler to create the default configuration only if there is no existing file.

**Comment by palisadoes** [comment]
It's still happening. Please review.

**Comment by palisadoes** [comment]
It seems fixed.
